namespace Zadanie5.Utils;

public enum RequestStatus
{
    SUCCESS =-1,
    ERROR_PRODUCT_DOESNT_EXIST = -2,
    ERROR_WHOLESALE_DOESNT_EXISTS = -3,
    ERROR_AMOUNT_DOESNT_EXIST = -4,
    ERROR_ORDER_DOESNT_EXIST = -5,
    ERROR_CREATED_AT_PARAMETER_GREATER_THEN_NATIVE = -6,
    ERROR_ORDER_ALREADY_DONE = -7
}
